CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    PasswordSalt NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE FoodCache (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FoodName NVARCHAR(255) NOT NULL,
    Barcode NVARCHAR(50) NULL,
    Calories INT NOT NULL,
    Protein DECIMAL(10,2) NOT NULL,
    Fat DECIMAL(10,2) NOT NULL,
    Carbohydrates DECIMAL(10,2) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE FoodEntries (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    FoodCacheId UNIQUEIDENTIFIER NULL REFERENCES FoodCache(Id),
    FoodName NVARCHAR(255) NOT NULL,
    Barcode NVARCHAR(50) NULL,
    Calories INT NOT NULL,
    Protein DECIMAL(10,2) NOT NULL,
    Fat DECIMAL(10,2) NOT NULL,
    Carbohydrates DECIMAL(10,2) NOT NULL,
    EatenAt DATETIME2 NOT NULL
);

CREATE TABLE UserGoals (
    UserId UNIQUEIDENTIFIER PRIMARY KEY REFERENCES Users(Id) ON DELETE CASCADE,
    DailyCalories INT NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_FoodCache_Barcode ON FoodCache(Barcode);
CREATE INDEX IX_FoodEntries_UserId_EatenAt ON FoodEntries(UserId, EatenAt);