CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    PasswordSalt NVARCHAR(255) NOT NULL
);

CREATE TABLE FoodCache (
    Barcode NVARCHAR(20) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Calories DECIMAL(10,2) NOT NULL,
    Protein DECIMAL(10,2) NOT NULL,
    Fat DECIMAL(10,2) NOT NULL,
    Carbohydrates DECIMAL(10,2) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL
);

CREATE TABLE FoodEntries (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    Name NVARCHAR(255) NOT NULL,
    Barcode NVARCHAR(20) NOT NULL,
    Grams DECIMAL(10,2) NOT NULL,
    Calories DECIMAL(10,2) NOT NULL,
    Protein DECIMAL(10,2) NOT NULL,
    Fat DECIMAL(10,2) NOT NULL,
    Carbohydrates DECIMAL(10,2) NOT NULL,
    EatenAt DATETIME2 NOT NULL
);

CREATE TABLE UserGoals (
    UserId UNIQUEIDENTIFIER PRIMARY KEY REFERENCES Users(Id) ON DELETE CASCADE,
    DailyCalorieLimit INT NOT NULL
);

CREATE INDEX IX_FoodCache_Name ON FoodCache(Name);
CREATE INDEX IX_FoodCache_Barcode ON FoodCache(Barcode);
CREATE INDEX IX_FoodEntries_UserId_EatenAt ON FoodEntries(UserId, EatenAt);